<section class="mt-3 card card-body">
    <h1>Gerenciar Professor</h1>
    <div class="mt-2">
        <a href="professor/novo" class="btn btn-outline-dark">Novo professor</a>
        <table class="table table-striped table-houver mt-4">
            <thead class="table-dark">
                <tr>
                    <th>#ID</th>
                    <th>Endereço</th>
                    <th>Status</th>
                    <th>Nome</th>
                    <th>Cpf</th>
                    <th>Açoes</th>
                </tr>
            </thead>
            <tbody>
                <?php
                    if(isset($professores) && sizeOf($professores) > 0){
                        foreach ($professores as $professor) {
                            echo "
                                <tr>
                                    <td>{$professor->id}</td>
                                    <td>{$professor->status}</td>
                                    <td>{$professor->endereco}</td>
                                    <td>{$professor->nome}</td>
                                    <td>{$professor->cpf}</td>
                                    <td>
                                        <a href='professores/editar?id={$professor->id}' class='btn btn-outline-warning'>Editar</a>
                                        <a href='professores/excluir?id={$professor->id}' type='button' onclick='' data-bs-toggle='modal' data-bs-target='#exampleModal' class='btn btn-outline-danger'>Excluir</a>
                                    </td>
                                <tr>
                            ";
                        }
                    }
                ?>
            </tbody>
        </table>
    </div>
</section>