<section class="mt-3 card card-body">
    <h1>Gerenciar Professor</h1>
    <div class="mt-2">
        <!-- <a href="professor/novo" class="btn btn-outline-dark">Novo professor</a> -->
        <table class="table table-striped table-houver mt-4">
            <thead class="table-dark">
                <tr>
                    <th>#ID</th>
                    <th>Nome</th>
                    <th>Matricula</th>
                    <th>CPF</th>
                    <th>Email</th>
                    <th>Açoes</th>
                </tr>
            </thead>
        </table>
    </div>
</section>