<section class="mt-3 card card-body">
    <h1>Gerenciar Cursos</h1>
    <div class="mt-2">
        <a href="curso/novo" class="btn btn-outline-dark">Cadastrar Curso</a>
        <table class="table table-striped table-houver mt-4">
            <thead class="table-dark">
                <tr>
                    <th>#ID</th>
                    <th>Nome</th>
                    <th>Professor</th>
                    <th>Periodo</th>
                    <th>Laboratorio</th>
                    <th>Açoes</th>
                </tr>
            </thead>
        </table>
    </div>
</section>