<section class="mt-3 card card-body">
    <h1>Gerenciar Alunos</h1>
    <div class="mt-2">
        <a href="alunos/novo" class="btn btn-outline-dark">Novo Aluno</a>
        <table class="table table-striped table-houver mt-4">
            <thead class="table-dark">
                <tr>
                    <th>#ID</th>
                    <th>Nome</th>
                    <th>Matricula</th>
                    <th>CPF</th>
                    <th>Email</th>
                    <th>Açoes</th>
                </tr>
            </thead>
            <tbody>
                <?php
                    foreach ($alunos as $aluno) {
                        echo "
                        <tr>
                        <td>{$aluno->id}</td>
                        <td>{$aluno->nome}</td>
                        <td>{$aluno->matricula}</td>
                        <td>{$aluno->cpf}</td>
                        <td>{$aluno->email}</td>
                         <td>
                            <a href='' class='btn btn-outline-warning'>Editar</a>
                            <button type='button' onclick='' data-bs-toggle='modal' data-bs-target='#exampleModal' class='btn btn-outline-danger'>Excluir</button>
                        </td>
                        <tr>
                        ";
                    }
                ?>
            </tbody>
        </table>
    </div>
</section>